export const DEFAULT_CHARACTER_SET =
  ' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:!?+-/&@';

export const DEFAULT_CUSTOM_MESSAGE =
  'ANALOG SENTINEL|MANUAL FEED READY|SET A MESSAGE IN THE CONTROL DECK';

export const ROTATION_INTERVAL_OPTIONS = [4000, 6000, 9000, 12000];
